##Prática/Desenvolvimento de **código** usando Regressão Logística

In [23]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model,datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import tensorflow.compat.v1 as tf
%matplotlib inline
import pandas as pd

In [ ]:
class Perceptron:
    def __init__(self, lr, epochs):
        self.lr = lr
        self.epochs = epochs
        self.weights = None
        self.bias = None

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z)) # Sigmoid

    def fit(self, X, y):
        num_features = X.shape[1]
        self.weights = np.zeros(num_features)
        self.bias = 0

        for _ in range(self.epochs):
            z = np.dot(X, self.weights) + self.bias

            predictions = self.sigmoid(z)

            dw = (1 / len(X)) * np.dot(X.T, (predictions - y))
            db = (1 / len(X)) * np.sum(predictions - y)

            self.weights -= self.lr * dw
            self.bias -= self.lr * db

    def predict(self, X):
        z = np.dot(X, self.weights) + self.bias
        predictions = self.sigmoid(z)
        return predictions


## Calculando o Banco de Dadso Iris.csv



In [ ]:
dataset = pd.read_csv('iris.csv')


dataset['Species'] = dataset['Name'].replace(['Iris-setosa', 'Iris-versicolor','Iris-virginica'], [1, 2, 3])

dataset['Species'].value_counts()

1    50
2    50
3    50
Name: Species, dtype: int64

# Inicializando o Perceptron

In [ ]:
X = dataset.loc[:, ['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth']]
y = dataset.loc[:, ['Species']]

In [ ]:
perceptron0 = Perceptron(0.01, 2000)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)


In [ ]:
#prediction0 = perceptron0.predict(X_test)
perceptron0.fit(X_train, y_train)

ValueError: Unable to coerce to Series, length must be 1: given 135

# Criando um Perceptron simples

In [146]:
import pandas as pd

dataset = pd.read_csv('iris.csv')


dataset['Species'] = dataset['Name'].replace(['Iris-setosa', 'Iris-versicolor','Iris-virginica'], [1, 2, 3])
dataset['Species'].value_counts()


#dataframe = pd.read_csv("housing.csv", delim_whitespace=True, header=None)
#dataset = dataframe.values


1    50
2    50
3    50
Name: Species, dtype: int64

## Função Sigmoid

In [13]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [147]:
import numpy as np
from sklearn import linear_model,datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix



def softmax(x):
  """
  Função de ativação softmax

  Args:
    x: Vetor de entrada

  Returns:
    Vetor de saída com as probabilidades de cada classe
  """

  exp_x = np.exp(x)
  sum_exp_x = np.sum(exp_x)
  return exp_x / sum_exp_x

def perceptron(x, w, b):
#  y = np.dot(x, w) + b
#  return softmax(y)
  y = np.dot(x, w) + b
  if y > 0:
    return 1
  else:
    return -1
  #y = sigmoid(np.dot(x, w) + b)
#  if y > 0.5:
#    return 1
#  else:
#    return -1
#  if y > 0.5:
#    return 1
#  elif y > 0.25:
#    return 2
#  else:
#    return 3

def treinar_perceptron(X, y, w, b, epochs, eta=0.1, shuffle=True):

  if shuffle:
    X = X.copy()
    np.random.shuffle(X)

  for epoch in range(epochs):
    for i in range(X.shape[0]):
      y_pred = perceptron(X[i], w, b)
      if y_pred != y[i]:
        w = w + eta * X[i] * y[i]
        b = b + eta * (y[i] - y_pred)

  return w, b

#def classificar(X, w, b):
#  y_pred = []
#  for x in X:
#    y_pred.append(perceptron(x, w, b))
#  return y_pred

def classificar(X, w, b):
  X_np = X.astype(np.float64)  # Indentation aligned with other lines
  y_pred = []
  for x in X_np:
    y_pred.append(perceptron(x, w, b))
  return np.array(y_pred)
"""
  Returns:
    Array NumPy de saídas classificadas
  """
"""
  y_pred = []
  for x in X:
    y_pred.append(perceptron(x, w, b))
  return np.array(y_pred)
"""


def calcular_acurácia(X, y, w, b):
  y_pred = classificar(X, w, b)
  acertos = 0
  for i in range(len(X)):
    if y_pred[i] == y[i]:
      acertos += 1
  return acertos / len(X)

def acur(X, y, y_pred):
  acertos = 0
  for i in range(len(X)):
    if y_pred[i] == y[i]:
      acertos += 1
  return acertos / len(X)

In [150]:
#Função de Teste

def criar_array_teste_treinamento(X, y, porcentagem_teste):
  """
  Cria um array numpy de teste e treinamento

  Args:
    X: Array numpy original
    y: Vetor de saídas desejadas original
    porcentagem_teste: Porcentagem de dados para o conjunto de teste

  Returns:
    X_teste: Array numpy de teste
    X_treinamento: Array numpy de treinamento
    y_teste: Vetor de saídas desejadas de teste
    y_treinamento: Vetor de saídas desejadas de treinamento
  """

  n_total = len(X)
  n_teste = int(n_total * porcentagem_teste)
  n_treinamento = n_total - n_teste

  X_teste = X[:n_teste]
  X_treinamento = X[n_teste:]
  y_teste = y[:n_teste]
  y_treinamento = y[n_teste:]

  return X_treinamento, X_teste, y_treinamento, y_teste

In [149]:


X = dataset.loc[:, ['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth']]
y = dataset.loc[:, ['Species']]
#X_train, X_test, y_train, y_test = criar_array_teste_treinamento(X, y, 1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)



In [134]:
#tf.compat.v1.disable_eager_execution()
#X = tf.placeholder(tf.float32, [None, 4])
#y = tf.placeholder(tf.float32, [None, 1])

#X_train_np = X_train.to_numpy()
#y_train_np = y_train.to_numpy()
#X_test_np = X_test.to_numpy()
#X_test_np = np.asarray(X_test_np, dtype='int32')

In [151]:

#X = np.array([[1, 1], [1, -1], [-1, 1], [-1, -1]])
#y = np.array([-1, 1, 1, -1])
w = np.zeros(X.shape[1])
b = 0.1
print(X_test_np)
w, b = treinar_perceptron(X_train_np, y_train_np, w, b, 100, 0.1, True)
y_pred = classificar(X_test_np, w, b)

#print(y_train_np)

print("Pesos finais:", w)
print("Bias final:", b)
print("Saídas classificadas:", y_pred)


[[5 2 5 2]
 [6 2 4 1]
 [5 4 1 0]
 [7 2 6 1]
 [5 3 1 0]
 [6 3 6 2]
 [5 3 1 0]
 [6 3 4 1]
 [6 2 4 1]
 [6 2 4 1]
 [6 2 5 1]
 [6 3 4 1]
 [6 2 4 1]
 [6 2 4 1]
 [6 2 4 1]]
Pesos finais: [1305.8  682.3  841.6  270.6]
Bias final: [134.1]
Saídas classificadas: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
